---
api_version: core/v2
type: CheckConfig
metadata:
  name: kubernetes-liveness
spec:
  command: >-
    http-check
    --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
    --trusted-ca-file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    --url https://kubernetes.default.svc:${KUBERNETES_SERVICE_PORT:-443}/livez?verbose
  runtime_assets:
    - sensu/http-checks:0.5.0
  env_vars: []
  secrets: []
  publish: true
  subscriptions:
    - kubernetes
    - kubernetes/apiserver
    - kubernetes/daemonset
  interval: 30
  round_robin: true
  proxy_entity_name: kube-apiserver
  pipelines: []

---
api_version: core/v2
type: CheckConfig
metadata:
  name: kubelet-metrics
spec:
  command: >-
    wget -q -O-
    http://127.0.0.1:10255/metrics
  runtime_assets: []
  env_vars: []
  secrets: []
  publish: true
  subscriptions:
    - kubelet
    - kubernetes/kubelet
    - kubernetes/daemonset
  interval: 30
  timeout: 10
  output_metric_format: prometheus_text
  output_metric_tags:
    - name: entity
      value: "{{ .name }}"
  pipelines: []

---
api_version: core/v2
type: CheckConfig
metadata:
  name: kubelet-probe-metrics
spec:
  command: >-
    wget -q -O-
    http://127.0.0.1:10255/metrics/probes
  runtime_assets: []
  env_vars: []
  secrets: []
  publish: true
  subscriptions:
    - kubelet
    - kubernetes/kubelet
    - kubernetes/daemonset
  interval: 30
  timeout: 10
  output_metric_format: prometheus_text
  output_metric_tags:
    - name: entity
      value: "{{ .name }}"
  pipelines: []

---
type: CheckConfig
api_version: core/v2
metadata:
  name: kubelet-cadvisor-metrics
spec:
  command: >-
    wget -q -O-
    http://127.0.0.1:10255/metrics/cadvisor
  runtime_assets: []
  env_vars: []
  secrets: []
  publish: true
  subscriptions:
    - kubelet
    - kubernetes/cadvisor
    - kubernetes/kubelet
    - kubernetes/daemonset
  interval: 30
  timeout: 10
  output_metric_format: prometheus_text
  output_metric_tags:
    - name: entity
      value: "{{ .name }}"
  pipelines: []

---
type: Asset
api_version: core/v2
metadata:
  name: sensu/http-checks:0.5.0
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/nixwiz/http-checks
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/nixwiz/http-checks
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 0.5.0
    io.sensu.bonsai.namespace: nixwiz
    io.sensu.bonsai.name: http-checks
    io.sensu.bonsai.tags: check, http
spec:
  builds:
    - url: https://assets.bonsai.sensu.io/cd4ae6bc1de70ba4e898d25596f2d50788759586/http-checks_0.5.0_linux_armv7.tar.gz
      sha512: b28f8c36caef5140f03f85882fb4a3fc4ce4fa045303d11e4392b54e31eb4f91eaa33f049d4582e4a3211479412ebc0affc89281b508a6204b11a9fed5282f31
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'armv7'
    - url: https://assets.bonsai.sensu.io/cd4ae6bc1de70ba4e898d25596f2d50788759586/http-checks_0.5.0_linux_arm64.tar.gz
      sha512: 7308f9c0dfc788eafe31a2a1dc8321469c9b2d436e581a5b747c6a67de292ec27dacef7060cb69d8034f0b1666b31c025c05b24df9e5c8d3f42c32e1d69b3890
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'arm64'
    - url: https://assets.bonsai.sensu.io/cd4ae6bc1de70ba4e898d25596f2d50788759586/http-checks_0.5.0_linux_386.tar.gz
      sha512: 6457583d2cd7d80a22ed6d57cf0375bff2db5a9a7f28904e0d5815bce5541107b0f9301bc5906c1b0896d89ea9c1307c8ca98547e3fb837c9662b851bc3cdfac
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == '386'
    - url: https://assets.bonsai.sensu.io/cd4ae6bc1de70ba4e898d25596f2d50788759586/http-checks_0.5.0_linux_amd64.tar.gz
      sha512: bc5fc3bfbb228f8813272789dcb2d15183dd2d593dd66a67a6cf364e251601f096d1c8b0b6fbede4880eab0eeeb11c6ab69b85adda7402af023bd3f1063d932b
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'amd64'
    - url: https://assets.bonsai.sensu.io/cd4ae6bc1de70ba4e898d25596f2d50788759586/http-checks_0.5.0_windows_amd64.tar.gz
      sha512: b936ca0afcaeca31a940d092cd801f71e2b59df69ade3419554158758b40d608af18a7141f301512388721512bf0965cd34f3f93c51e6a1ca1a2c6c48c616509
      filters:
        - entity.system.os == 'windows'
        - entity.system.arch == 'amd64'
    - url: https://assets.bonsai.sensu.io/cd4ae6bc1de70ba4e898d25596f2d50788759586/http-checks_0.5.0_darwin_amd64.tar.gz
      sha512: 38e6cb8b79c33250bb0b676e7bfb77e2982667873d884c8e3e6e2a2582c15a58854d2e6aecaec96a34c07080682b3129b807d94a761f95efd1bb8bb736e67aed
      filters:
        - entity.system.os == 'darwin'
        - entity.system.arch == 'amd64'
