---
name: 'Sensu Catalog Validator'
description: 'Validate a Sensu Catalog'
author: 'sensu'
inputs:
  catalog-api-version:
    description: 'The version of the API tool to use'
    required: true
    default: '0.1.0-alpha.14'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.catalog-api-version }}
branding:
  icon: 'globe'
  color: 'green'
