---
api_version: catalog/v1
type: Integration
metadata:
  namespace: ansible
  name: ansible-tower-remediation
spec:
  class: enterprise
  provider: remediation
  display_name: Ansible Tower
  short_description: Triggers Ansible Tower job templates for automated remediation.
  tags:
    - ansible
    - remediation
    - self healing
    - automation
  contributors:
    - "@sensu"
    - "@calebhailey"
    - "@jspaleta"
  prompts:
    - type: section
      title: Ansible Tower API Configuration
    - type: markdown
      body: |
        This integration requires a Ansible Tower API Host and API Token for API Authentication.

        Please visit [Ansible Tower API OAuth Guide] for more information.

        [Ansible Tower API OAuth Guide]: https://docs.ansible.com/ansible-tower/latest/html/administration/oauth2_token_auth.html
    - type: question
      name: api_host
      required: true
      input:
        type: string
        title: Ansible Tower API Host
        description: >-
          Provide the API Host (i.e. hostname or IP address)
        default: "127.0.0.1"
    - type: question
      name: ansible_tower_api_token
      required: true
      input:
        type: string
        title: Ansible Tower API Token
        description: >-
          Ansible Tower API Token
  resource_patches:
    - resource:
        api_version: core/v2
        type: Handler
        name: ansible-tower
      patches:
        - path: /spec/env_vars/0
          op: replace
          value: ANSIBLE_HOST=127.0.0.1
        - path: /spec/env_vars/-
          op: add
          value: "ANSIBLE_TOKEN=[[ansible_tower_api_token]]"
