---
name: 'Sensu Catalog Workflow'

on:
  workflow_call:
    inputs:
      cache_key:
        type: string
        default: |
          ${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}
      catalog_api_version:
        type: string
        default: '0.1.0-alpha.13'
      catalog_temp_dir:
        type: string
        default: './tmp'
      catalog_snapshot:
        type: boolean
        default: false
      catalog_version_file:
        type: string
    secrets:
      aws_s3_bucket:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true

jobs:
  validate:
    name: 'Validate Sensu Catalog'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0  # The whole repository must be cloned
      - name: Run Sensu Catalog validation
        uses: ./.github/actions/validate-catalog
        with:
          catalog-api-version: ${{ inputs.catalog_api_version }}

  generate:
    name: 'Generate Sensu Catalog API'
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      release-dir: ${{ steps.generate-api.outputs.release-dir }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0  # The whole repository must be cloned
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ${{ inputs.catalog_temp_dir }}
          key: ${{ inputs.cache_key }}
      - name: Run Sensu Catalog API generation
        uses: ./.github/actions/generate-catalog-api
        id: generate-api
        with:
          catalog-api-version: ${{ inputs.catalog_api_version }}
          snapshot: ${{ inputs.catalog_snapshot }}
          temp-dir: ${{ inputs.catalog_temp_dir }}

  publish:
    name: 'Publish Sensu Catalog API'
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0  # The whole repository must be cloned
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ inputs.catalog_temp_dir }}
          key: ${{ inputs.cache_key }}
      - name: Run Sensu Catalog API publisher
        uses: ./.github/actions/publish-catalog-api
        with:
          release-dir: ${{ needs.generate.outputs.release-dir }}
          version-file: ${{ inputs.catalog_version_file }}
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
